apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: ahmedmh03.work@gmail.com
    
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Secret to store your ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    
    # Solvers - how to prove domain ownership
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z05803441P04TCJ0P5ELV